### ISSUE TITLE
Re-enable XPI verification

### ISSUE THREAD

**Issue by joshuayabut** [IndependentOnion/rotor-browser#7]
XPI verification was disabled to allow us to meet the ship date. We need to obtain a code signing certificate and then re-enable XPI signature verification.

**Comment by indornet** [comment]
The code signing certificate has been purchased (but not issued yet). I need to stop by the notary tomorrow to setup our physical address and then I'll get the cert issued.

**Comment by joshuayabut** [comment]
The code signing certificate has been purchased (but not issued yet). I need to stop by the notary tomorrow to setup our physical address and then I'll get the cert issued.

**Comment by joshuayabut** [comment]
This can actually be reverted. Tor Incorporated does not actually codesign their browser extensions and they are exempt from checking.
